# Form implementation generated from reading ui file 'create.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_GameCreateWindow(object):
    def setupUi(self, GameCreateWindow):
        GameCreateWindow.setObjectName("GameCreateWindow")
        GameCreateWindow.resize(416, 276)
        GameCreateWindow.setStyleSheet("backgroud-color: rgb(215, 225, 255)")
        self.centralwidget = QtWidgets.QWidget(GameCreateWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(120, 80, 181, 121))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.gridLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.game_name = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.game_name.setStyleSheet("border: 1px solid rgb(31, 44, 56);\n"
"border-radius: 3px;")
        self.game_name.setText("")
        self.game_name.setObjectName("game_name")
        self.verticalLayout.addWidget(self.game_name)
        self.guessing_word = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.guessing_word.setStyleSheet("border: 1px solid rgb(31, 44, 56);\n"
"border-radius: 3px;")
        self.guessing_word.setObjectName("guessing_word")
        self.verticalLayout.addWidget(self.guessing_word)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(120, 30, 181, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(31, 44, 56)")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.create_button = QtWidgets.QPushButton(self.centralwidget)
        self.create_button.setGeometry(QtCore.QRect(180, 220, 56, 20))
        self.create_button.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.create_button.setStyleSheet("background: rgb(31, 44, 56);\n"
"border-radius: 3;\n"
"color: white;")
        self.create_button.setIconSize(QtCore.QSize(12, 14))
        self.create_button.setObjectName("create_button")
        GameCreateWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(GameCreateWindow)
        QtCore.QMetaObject.connectSlotsByName(GameCreateWindow)

    def retranslateUi(self, GameCreateWindow):
        _translate = QtCore.QCoreApplication.translate
        GameCreateWindow.setWindowTitle(_translate("GameCreateWindow", "MainWindow"))
        self.game_name.setPlaceholderText(_translate("GameCreateWindow", "Type game\'s name"))
        self.guessing_word.setPlaceholderText(_translate("GameCreateWindow", "Type guessing word"))
        self.label.setText(_translate("GameCreateWindow", "CREATING GAME"))
        self.create_button.setText(_translate("GameCreateWindow", "CREATE"))
