# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_EndWindow(object):
    def setupUi(self, EndWindow):
        EndWindow.setObjectName("EndWindow")
        EndWindow.setWindowModality(QtCore.Qt.WindowModality.WindowModal)
        EndWindow.resize(587, 562)
        EndWindow.setWindowTitle("Hangman - Game over")
        EndWindow.setStyleSheet("QPushButton{background:rgb(31, 44, 56);border-radius:3;color:white;padding:4px;margin:4px;}QPushButton:hover{border:1px solid white;}QPushButton:pressed{color:black;background:white;}")
        self.main_widget = QtWidgets.QWidget(EndWindow)
        self.main_widget.setObjectName("main_widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.main_widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.message_label = QtWidgets.QLabel(self.main_widget)
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(12)
        self.message_label.setFont(font)
        self.message_label.setText("")
        self.message_label.setObjectName("message_label")
        self.verticalLayout.addWidget(self.message_label, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.go_menu = QtWidgets.QPushButton(self.main_widget)
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(12)
        self.go_menu.setFont(font)
        self.go_menu.setText("Go to main menu")
        self.go_menu.setObjectName("go_menu")
        self.verticalLayout.addWidget(self.go_menu, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        EndWindow.setCentralWidget(self.main_widget)

        self.retranslateUi(EndWindow)
        QtCore.QMetaObject.connectSlotsByName(EndWindow)

    def retranslateUi(self, EndWindow):
        pass
